// <auto-generated />
using ASS02EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASS02EF.Migrations
{
    [DbContext(typeof(ApplicationDbContest))]
    [Migration("20260416124009_update orginazer and profile ")]
    partial class updateorginazerandprofile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASS02EF.Models.Orginazer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("companyname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isverfied")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("orginazers");
                });

            modelBuilder.Entity("ASS02EF.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("biography")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orginazerID")
                        .HasColumnType("int");

                    b.Property<string>("website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("orginazerID")
                        .IsUnique();

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("ASS02EF.Models.Profile", b =>
                {
                    b.HasOne("ASS02EF.Models.Orginazer", "proOrginazer")
                        .WithOne("orgprofile")
                        .HasForeignKey("ASS02EF.Models.Profile", "orginazerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("proOrginazer");
                });

            modelBuilder.Entity("ASS02EF.Models.Orginazer", b =>
                {
                    b.Navigation("orgprofile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
