// <auto-generated />
using System;
using ASS02EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASS02EF.Migrations
{
    [DbContext(typeof(ApplicationDbContest))]
    [Migration("20260416130738_add event and attende and badge")]
    partial class addeventandattendeandbadge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASS02EF.Models.Attendee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("attendees");
                });

            modelBuilder.Entity("ASS02EF.Models.Badge", b =>
                {
                    b.Property<int>("badgenumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("badgenumber"));

                    b.Property<int>("attendeid")
                        .HasColumnType("int");

                    b.Property<DateTime>("issueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("tier")
                        .HasColumnType("int");

                    b.HasKey("badgenumber");

                    b.HasIndex("attendeid")
                        .IsUnique();

                    b.ToTable("badges");
                });

            modelBuilder.Entity("ASS02EF.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("MaxAttendees")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("startdate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("events");
                });

            modelBuilder.Entity("ASS02EF.Models.Orginazer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("companyname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isverfied")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("orginazers");
                });

            modelBuilder.Entity("ASS02EF.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("biography")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orginazerID")
                        .HasColumnType("int");

                    b.Property<string>("website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("orginazerID")
                        .IsUnique();

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("ASS02EF.Models.Badge", b =>
                {
                    b.HasOne("ASS02EF.Models.Attendee", "badAttendee")
                        .WithOne("attBadge")
                        .HasForeignKey("ASS02EF.Models.Badge", "attendeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("badAttendee");
                });

            modelBuilder.Entity("ASS02EF.Models.Profile", b =>
                {
                    b.HasOne("ASS02EF.Models.Orginazer", "proOrginazer")
                        .WithOne("orgprofile")
                        .HasForeignKey("ASS02EF.Models.Profile", "orginazerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("proOrginazer");
                });

            modelBuilder.Entity("ASS02EF.Models.Attendee", b =>
                {
                    b.Navigation("attBadge")
                        .IsRequired();
                });

            modelBuilder.Entity("ASS02EF.Models.Orginazer", b =>
                {
                    b.Navigation("orgprofile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
